### ISSUE TITLE
Pictures are missing from Wiki

### ISSUE THREAD

**Issue by ulbivin** [marabouboy/FLAME#3]
Hi,

It seems all pictures are missing from the Wiki on FLAME.

**Comment by marabouboy** [comment]
Hi,
Pictures should be up now.
If not, just comment on this thread.

There was an issue with wrong permissions and sources.


Thank you for flagging this error!

**Comment by ulbivin** [comment]
Hi Marabouboy,

Pictures are online now - thank you for your swift action!
